def print_in_various_formats(letter : String) : Unit = {
	val letter_bytes = letter.getBytes()
	println("As UTF-8:\t\t" + new String(letter_bytes, "utf-8"))
	println("As cp1252:\t\t" + new String(letter_bytes, "cp1252"))
	println("As ISO-8859-2:\t\t" + new String(letter_bytes, "ISO-8859-2"))
}

print_in_various_formats("á")
println()
print_in_various_formats("Á")
println()
print_in_various_formats("é")
println()
print_in_various_formats("É")
println()
print_in_various_formats("í")
println()
print_in_various_formats("Í")
println()
print_in_various_formats("ó")
println()
print_in_various_formats("Ó")
println()
print_in_various_formats("ú")
println()
print_in_various_formats("Ú")
println()
print_in_various_formats("ñ")
println()
print_in_various_formats("Ñ")
